[package]
name = "settings-example"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.15"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1", features = ["derive"] }

[build-dependencies]
